#!/usr/bin/python
import time
import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
GPIO.setup(18, GPIO.OUT)
for x in range(1,10):
	GPIO.output(18, False)
	time.sleep(1)
	GPIO.output(18, True)
	time.sleep(1)
